<x-app-layout>

    <x-slot name="header">
        <h2 class="font-semibold text-xl leading-tight">
            Yang Wang's {{ __('Joke DB') }}
        </h2>
    </x-slot>


    <article class="-mx-4">
        <header class="bg-zinc-700 text-zinc-200 rounded-t-lg -mx-4 -mt-8 p-8 text-2xl font-bold mb-8">
            <h2>Welcome</h2>
            <p class="text-sm">{{ now() }}</p>
        </header>

        <div class="flex flex-col flex-wrap my-4 mt-8">
            <section class="mx-auto w-1/2 m-8 bg-zinc-200 text-sm  text-zinc-800 p-4 rounded-lg shadow">
                <header class="-mx-4 bg-zinc-700 text-zinc-200 text-md text-semibold p-4 -mt-4 mb-4 rounded-t flex-0">
                    <h4>
                        About the Developer
                    </h4>
                </header>
                <p>My name is YANG WANG. Currently, I am studying for a Full Stack Web Development
                    diploma, which I expect to complete in June 2024. I have 5 years of experience working in tech
                    companies, mainly focusing on mobile game marketing and promotion.</p>
                <br>
                <p>This website, Yang's Jokes DB, is a SaaS project built using Laravel framework and serves as part of my web
                    development learning journey. It reflects my dedication to mastering database-driven web
                    applications and is a key milestone in my development career.</p>
            </section>

            <section class="mx-auto w-1/2 m-8 bg-zinc-200 text-sm  text-zinc-800 p-4 rounded-lg shadow">
                <header class="-mx-4 bg-zinc-700 text-zinc-200 text-md text-semibold p-4 -mt-4 mb-4 rounded-t flex-0">
                    <h4>
                        About the Project
                    </h4>
                </header>
                <!--                Content generated by Mistral at:-->
                <!--                https://chat.mistral.ai/chat/65057c4d-bb8f-481c-b5e0-da18ee1a5989-->
                <dl class="grid grid-cols-5 gap-2">
                    <dt class="col-span-1 font-bold">Project Title:</dt>
                    <dd class="col-span-4">
                        <p class="text-zinc-900">
                            Simple Jokes System - Laravel
                        </p>
                    </dd>
                    <dt class="col-span-1 font-bold">Objective:</dt>
                    <dd class="col-span-4">
                        <p class="text-zinc-900">
                            Develop a simple jokes system using a Laravel & SQL micro-framework. The system will allow users
                            to register, log in, and manage jokes and other users. Users will be able to add, edit, and
                            delete jokes and users they have created. Additionally, the system will support optional
                            category management. </p>
                    </dd>
                    <dt class="col-span-1 font-bold">Key Features:</dt>
                    <dd class="col-span-4">
                        <ol class="list-disc">
                            <li>User registration, login, and logout.</li>
                            <li>User management (browse, read one, edit, add, delete, search/filter).</li>
                            <li>Joke management (browse, read one, edit, add, delete, search/filter).</li>
                            <li>Registered and authenticated users can add, edit, and delete users and jokes they have created.</li>
                            <li>Optional category management (browse, read one, edit, add, delete).</li>
                        </ol>
                    </dd>
                    <dt class="col-span-1 font-bold">Technologies:</dt>
                    <dd class="col-span-4">
                        <ul class="list-disc">
                            <li>PHP MVC micro-framework</li>
                            <li>Laravel framework</li>
                            <li>Blade template</li>
                            <li>MySQL v8+ / MariaDB 10+</li>
{{--                            <li>Markdown to HTML conversion package (recommended: Parsedown)</li>--}}
                        </ul>
                    </dd>
                </dl>
            </section>

            <section class="mx-auto w-1/2 m-8 bg-zinc-200 text-sm  text-zinc-800 p-4 rounded-lg shadow">
                <header class="-mx-4 bg-zinc-700 text-zinc-200 text-md text-semibold p-4 -mt-4 mb-4 rounded-t flex-0">
                    <h4>
                        Useful References
                    </h4>
                </header>
                <dl class="grid grid-cols-5 gap-2">
                    <dt class="col-span-1">Tutorial Part 1:</dt>
                    <dd class="col-span-4">
                        <a href="https://github.com/AdyGCode/SaaS-FED-Notes/tree/main/session-07"
                           class="underline underline-offset-2 text-zinc-900 rounded border-2 border-transparent hover:text-white hover:bg-blue-500 hover:border-blue-500">
                            https://github.com/AdyGCode/SaaS-FED-Notes/tree/main/session-07
                        </a>
                    </dd>
                    <dt class="col-span-1">Tutorial Part 2:</dt>
                    <dd class="col-span-4">
                        <a href="https://github.com/AdyGCode/SaaS-FED-Notes/tree/main/session-07"
                           class="underline underline-offset-2 text-zinc-900 rounded border-2 border-transparent hover:text-white hover:bg-purple-500 hover:border-purple-500">
                            https://github.com/AdyGCode/SaaS-FED-Notes/tree/main/session-07
                        </a>
                    </dd>
                    <dt class="col-span-1">Source Code:</dt>
                    <dd class="col-span-4">
                        <a href="https://github.com/AdyGCode/XXX-PHP-MVC-Jokes-Demo"
                           class="underline underline-offset-2 text-zinc-900 rounded border-2 border-transparent hover:text-white hover:bg-red-500 hover:border-red-500">
                            https://github.com/AdyGCode/XXX-PHP-MVC-Jokes-Demo
                        </a>
                    </dd>
                    <dt class="col-span-1">HelpDesk</dt>
                    <dd class="col-span-4">
                        <a href="https://help.screencraft.net.au"
                           class="underline underline-offset-2 text-zinc-900 rounded border-2 border-transparent hover:text-white hover:bg-orange-500 hover:border-orange-500">
                            https://help.screencraft.net.au
                        </a>
                    </dd>
                    <dt class="col-span-1">HelpDesk FAQs</dt>
                    <dd class="col-span-4">
                        <a href="https://help.screencraft.net.au/hc/2680392001"
                           class="underline underline-offset-2 text-zinc-900 rounded border-2 border-transparent hover:text-white hover:bg-amber-500 hover:border-amber-500">
                            https://help.screencraft.net.au/hc/2680392001
                        </a>
                    </dd>
                    <dt class="col-span-1">Make a Request</dt>
                    <dd class="col-span-4">
                        <a href="https://help.screencraft.net.au/help/2680392001"
                           class="underline underline-offset-2 text-zinc-900 rounded border-2 border-transparent hover:text-white hover:bg-lime-500 hover:border-lime-500">
                            https://help.screencraft.net.au/help/2680392001</a>
                        (TAFE Students only)
                    </dd>
                </dl>

            </section>
        </div>

    </article>

</x-app-layout>
